FROM python:3.9-slim AS bob

WORKDIR /app
COPY req.txt .
RUN pip install --target=/app/deps/ -r req.txt

FROM gcr.io/distroless/python3

WORKDIR /app
COPY --from=bob /app/deps /app/deps
COPY . .

ENV PYTHONPATH="/app/deps"

EXPOSE 5000

CMD ["ap.py"]